### ISSUE TITLE
Nie działa docker-compose z seq

### ISSUE THREAD

**Issue by sulmar** [sulmar/vavatech-dotnet-6-microservices-202210#11]

**Comment by sulmar** [comment]
``` yaml
version: '3.4'

services:
  seq:
      image: datalust/seq:latest
      ports:
        - "5341:80"
      environment:
        - ACCEPT_EULA=Y
      restart: unless-stopped
      volumes:
        - ./seq-data:/data
```
